# Generated by Django 4.2.4 on 2023-10-05 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('region', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('lat', models.DecimalField(decimal_places=2, max_digits=8)),
                ('lon', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tz_id', models.CharField(max_length=255)),
                ('localtime_epoch', models.BigIntegerField()),
                ('localtime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='current_weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated_epoch', models.BigIntegerField()),
                ('last_updated', models.DateTimeField()),
                ('temp_c', models.DecimalField(decimal_places=2, max_digits=5)),
                ('temp_f', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_day', models.SmallIntegerField()),
                ('condition_text', models.CharField(max_length=255)),
                ('condition_icon', models.CharField(max_length=255)),
                ('condition_code', models.IntegerField()),
                ('wind_mph', models.DecimalField(decimal_places=2, max_digits=5)),
                ('wind_kph', models.DecimalField(decimal_places=2, max_digits=5)),
                ('wind_degree', models.IntegerField()),
                ('wind_dir', models.CharField(max_length=255)),
                ('pressure_mb', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pressure_in', models.DecimalField(decimal_places=2, max_digits=6)),
                ('precip_mm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('precip_in', models.DecimalField(decimal_places=2, max_digits=5)),
                ('humidity', models.IntegerField()),
                ('cloud', models.IntegerField()),
                ('feelslike_c', models.DecimalField(decimal_places=2, max_digits=5)),
                ('feelslike_f', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vis_km', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vis_miles', models.DecimalField(decimal_places=2, max_digits=5)),
                ('uv', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gust_mph', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gust_kph', models.DecimalField(decimal_places=2, max_digits=5)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.city')),
            ],
        ),
    ]
