# Generated by Django 4.2.4 on 2023-10-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='localtime',
            field=models.DateTimeField(null=True),
        ),
    ]
