# Generated by Django 4.2.4 on 2023-10-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_alter_city_localtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='current_weather',
            name='last_updated',
            field=models.DateTimeField(null=True),
        ),
    ]
