# Generated by Django 4.2.4 on 2023-10-31 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_alter_current_weather_last_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='localtime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='current_weather',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
